"""create a table

Revision ID: 589150a6fc49
Revises: 
Create Date: 2022-03-25 18:12:19.700839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589150a6fc49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_expenses')
    # ### end Alembic commands ###
